### ISSUE TITLE
Call to undefined function imageantialias()

### ISSUE THREAD

**Issue by dvmada** [iionly/identicon#1]
Hi,

After install and activated in elgg 1.9, here the msg :
`Fatal error: Call to undefined function imageantialias() in /homesite/elgg/mod/identicon/start.php on line 408.`

I searched and couldn't find any imageantialias() definition in the all /mod directory
missing something ?
thx

**Comment by iionly** [comment]
imageantialias() is a function included in the php gd extension. But it might depend on the version of php and the GD extension if imageantialias() is available or not. In any case the version of php and the version of the GD extension should match. It might also be necessary to upgrade php and the GD extension if it fails to work.

From within the identicon plugin there's nothing that could be done to solve this. The only possibility would be to comment out this line in the code to prevent usage of the imageantialias(). The identicon images might look slightly worse but there shouldn't be any major issues otherwise.

**Comment by dvmada** [comment]
ok thx
funny, but GD is installed and up-to-date.
I'll try to use imagick
thx

**Comment by iionly** [comment]
I'm afraid imagick won't help you. The identicon plugin uses only the GD image library.

**Comment by dvmada** [comment]
hmmm. ok.
identicon use GD but can work even if I set imagick in Tidypics ? it's independant, right ?
I mean, the selection of the image library in tidypics don't interfer with identicon ?

**Comment by iionly** [comment]
The image library you select on the Tidypics settings page will only be used by Tidypics itself. The identicon plugin (and also Elgg itself on uploading of profile and group images and on uploading of images to the files section) will always use the GD php extension and the image library selected for Tidypics won't interfere (and I would suggest to always use the alternatives to the GD extension for Tidypics as they require less memory and give at least equal results regarding quality when the image thumbnails are created).

For getting the identicon plugin to work you can comment out the lines where the imageantialias() function is used. As I mentioned, I don't know how the resulting images will look then. The only other possibility is getting a GD php extension with a working imageantialias() function installed on the server. Maybe it helps to upgrade php and the GD extension to a newer version if possible. Unfortunately, I can't give any specific advice here regarding which version to choose and what might specifically to do in selecting a suitable version. It depends a lot on what OS is installed on the server and from what sources php is installed. Maybe the support of your webhoster could help you out here better.

**Comment by dvmada** [comment]
Ok clear.
thanks a lot for your response.
